dist: trusty
sudo: false
language: ruby
cache: bundler

env:
  - VAULT_VERSION=0.6.4
  - VAULT_VERSION=0.5.3

before_install:
  - curl -sLo vault.zip https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_linux_amd64.zip
  - unzip vault.zip
  - mkdir ~/bin
  - mv vault ~/bin
  - export PATH="~/bin:$PATH"

branches:
  only:
    - master

rvm:
  - 2.2
  - 2.3
  - 2.4
